#!/bin/sh
set -e
# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if test $(git diff --cached --name-only --diff-filter=A -z HEAD |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

EOF
	exit 1
fi

if npx prettier -c $(git status --porcelain |sed 's/[^ ]* -> //'|grep "^[^ D]" |awk '{print $2}')
then
	echo "source code is pretty"
else
	echo "source code is not pretty, fix that before commit"
	exit 1
fi

npm run test

exec git diff-index --check --cached HEAD --
